name: Cargo test

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:
    branches:
    - db_actions
env: 
  CARGO_TERM_COLOR: always
  TEST_DATABASE_URL: "0.0.0.0:5432/hive-test"

jobs:
  build_and_test:
    name: Rust project - latest
    runs-on: ubuntu-latest
    services:
    
      postgres:
        # Docker Hub image
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: hive
          POSTGRES_DB: hive-test
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
            # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        with:
          command: test
